<a href="https://colab.research.google.com/github/sashmos/Data-Mining-Homework/blob/main/1.%20%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/1_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [2]:
import numpy as np
print('numpy version: ' + np.__version__)

numpy version: 1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
vector = np.full(7, 7)
print(vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
vector = np.arange(10, 102, 2)
print(vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
random_array = np.random.rand(10)
print(random_array)
reversed = random_array[::-1]
print('перевернутый массив:\n',reversed)

[0.11014974 0.63550641 0.49704809 0.21022267 0.85486281 0.58718694
 0.81492646 0.65552744 0.32305317 0.82920262]
перевернутый массив:
 [0.82920262 0.32305317 0.65552744 0.81492646 0.58718694 0.85486281
 0.21022267 0.49704809 0.63550641 0.11014974]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix = np.arange(9).reshape(3, 3)
print(matrix) # (9 не войдет в матрицу)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
matrix = np.eye(4, k = 1)
print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
matrix = np.random.randint(0,100, (10, 10))
print("\n матрица случайных чисел: \n" , matrix)
row_avg = matrix.mean(axis=1, keepdims=True)
print("\n Среднее значение по всем строкам: \n" , row_avg)
matrix = matrix - row_avg # отнимаем среднее по всем строкам из каждого эл-а строки
print("\n нормализованная матрица случайных чисел: \n "  , matrix)


 матрица случайных чисел: 
 [[32 26 25 48 90  5 19 93 83 11]
 [96 46 30 72 13 51 29 66 35  1]
 [ 2 93 58 52 71  4 14 32  4 92]
 [51 53 17 89 10 62 16 28 70 13]
 [37 72 49 53 37 27 94 62 11 83]
 [61 59 98 44 69 85  5 93 26 24]
 [21  3 54 21 37 45 77 64 75 65]
 [61 75 61 79 85 19 73 21 29 43]
 [61 67 86 68 61 34 77 16  3 49]
 [48 32 47  2 52  1 43 16  0 29]]

 Среднее значение по всем строкам: 
 [[43.2]
 [43.9]
 [42.2]
 [40.9]
 [52.5]
 [56.4]
 [46.2]
 [54.6]
 [52.2]
 [27. ]]

 нормализованная матрица случайных чисел: 
  [[-11.2 -17.2 -18.2   4.8  46.8 -38.2 -24.2  49.8  39.8 -32.2]
 [ 52.1   2.1 -13.9  28.1 -30.9   7.1 -14.9  22.1  -8.9 -42.9]
 [-40.2  50.8  15.8   9.8  28.8 -38.2 -28.2 -10.2 -38.2  49.8]
 [ 10.1  12.1 -23.9  48.1 -30.9  21.1 -24.9 -12.9  29.1 -27.9]
 [-15.5  19.5  -3.5   0.5 -15.5 -25.5  41.5   9.5 -41.5  30.5]
 [  4.6   2.6  41.6 -12.4  12.6  28.6 -51.4  36.6 -30.4 -32.4]
 [-25.2 -43.2   7.8 -25.2  -9.2  -1.2  30.8  17.8  28.8  18.8]
 [  6.4  20.4   6.4  24.4  30.4 -3

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [3]:
matrix = np.random.randint(0,100, (10, 10))
print("\n матрица случайных чисел: \n" , matrix)
column_medians  = np.median(matrix, axis=0, keepdims=True)
print("\n медиана по всем столбцам: \n" , column_medians)
matrix = matrix - column_medians # отнимаем медиану по всем столбцам из каждого эл-а
print("\n нормализованная матрица случайных чисел: \n "  , matrix)


 матрица случайных чисел: 
 [[61 51 21 90 37 20  8 63 42  2]
 [94 75 22 33 40 10 89 50 86 75]
 [84  7 38 75 53  5 81 55 37 60]
 [45 31 62 45 10  2 78  3 46 96]
 [82 11 36 95 49 32 13 36  0 92]
 [87 49 24 74 76 33 44 70 48  4]
 [ 2 38 93 27 54 19 63 48 44 22]
 [ 2 45 87 87 47  0 75 23 11 58]
 [12 28 70 91 59 64 71  2 89 23]
 [88 65 86 20 65 47  2 42 55 61]]

 медиана по всем столбцам: 
 [[71.5 41.5 50.  74.5 51.  19.5 67.  45.  45.  59. ]]

 нормализованная матрица случайных чисел: 
  [[-10.5   9.5 -29.   15.5 -14.    0.5 -59.   18.   -3.  -57. ]
 [ 22.5  33.5 -28.  -41.5 -11.   -9.5  22.    5.   41.   16. ]
 [ 12.5 -34.5 -12.    0.5   2.  -14.5  14.   10.   -8.    1. ]
 [-26.5 -10.5  12.  -29.5 -41.  -17.5  11.  -42.    1.   37. ]
 [ 10.5 -30.5 -14.   20.5  -2.   12.5 -54.   -9.  -45.   33. ]
 [ 15.5   7.5 -26.   -0.5  25.   13.5 -23.   25.    3.  -55. ]
 [-69.5  -3.5  43.  -47.5   3.   -0.5  -4.    3.   -1.  -37. ]
 [-69.5   3.5  37.   12.5  -4.  -19.5   8.  -22.  -34.   -1. ]
 [-59.

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix = np.random.randint(0,100, (5, 5))
print("исходная матрица: \n ", matrix)

# вычисляем максимумы и минимумы по строкам
row_max = matrix.max(axis=1, keepdims=True)
row_min = matrix.min(axis=1, keepdims=True)
print("\n максимумы в строках: \n ", row_max)
print("\n мимнимумы в строках: \n ", row_min)

# создаем матрицу 5x7, добавляя столбцы максимумов и минимумов
matrix = np.hstack((matrix, row_max, row_min))
print(" \n расширенная матрица: \n ",matrix)

исходная матрица: 
  [[14 12  9 97 64]
 [57 74 69 89 34]
 [89 32 24 59 37]
 [21 96 32 88  8]
 [ 4 50 45 22 16]]

 максимумы в строках: 
  [[97]
 [89]
 [89]
 [96]
 [50]]

 мимнимумы в строках: 
  [[ 9]
 [34]
 [24]
 [ 8]
 [ 4]]
 
 расширенная матрица: 
  [[14 12  9 97 64 97  9]
 [57 74 69 89 34 89 34]
 [89 32 24 59 37 89 24]
 [21 96 32 88  8 96  8]
 [ 4 50 45 22 16 50  4]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [20]:
vector_numbers = np.arange(1, 51)

# Вектор нечетных чисел
odd_vector = vector_numbers[vector_numbers % 2 != 0]

# Вектор четных чисел
even_vector = vector_numbers[vector_numbers % 2 == 0]

# Преобразуем векторы в матрицы
odd_matrix = odd_vector.reshape(1, -1)
even_matrix = even_vector.reshape(1, -1)
print( 'матрица четных чисел \n',odd_matrix)
print( '\n матрица нечетных чисел \n',even_matrix)

matrix = np.dot(even_matrix, odd_matrix.T)
print( '\n Умножение матриц \n',matrix)

inv_matrix = np.linalg.inv(matrix)
print( '\n Обратная матрица \n',inv_matrix)


матрица четных чисел 
 [[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
  49]]

 матрица нечетных чисел 
 [[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]

 Умножение матриц 
 [[21450]]

 Обратная матрица 
 [[4.66200466e-05]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
chessboard_matrix = np.zeros((8, 8), dtype=int)
# Присваиваем 1 эл-ам с четными индексами в строке и нечетными в столбце
chessboard_matrix[1::2, ::2] = 1
# Присваиваем 1 эл-ам с нечетными индексами в строке и четными в столбце
chessboard_matrix[::2, 1::2] = 1

print(chessboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
